name: Build & Release Packs

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          for PACK in $(ls); do
            echo "Building $PACK"
            jq ".version |= \"$(echo $GITHUB_REF_NAME | sed 's/v//')\"" $PACK/package.json > $PACK/package.json.tmp
            mv $PACK/package.json.tmp $PACK/package.json
            tar -czvf $PACK.crbl -C $PACK/ .
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          files: |
            *.crbl

  deploy:
    uses: ./.github/workflows/deploy-pack.yml
    needs: build
    with:
      packs: '*'
      worker_group: 'default'