name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          pwd
          ls -lah
          for PACK in $(ls); do
            jq ".version |= \"$(echo $GITHUB_REF_NAME | sed 's/v//')\"" $PACK/package.json > $PACK/package.json.tmp
            mv $PACK/package.json.tmp $PACK/package.json
            tar -czf $PACK.crbl --strip-components 1 $PACK/
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.crbl
