name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          apt update && apt install -y jq
          mkdir -p build
          for PACK in $(ls); do
            cd $PACK
            jq ".version |= \"$(echo $GITHUB_REF_NAME | sed 's/v//')\"" package.json > package.json.tmp
            mv package.json.tmp package.json
            tar -czf ../build/${PACK}.crbl .
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.crbl
