name: Tests
run-name: Run tests and checks
on:
  pull_request:
    branches:
      - prod
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run tests
        run: pytest --junitxml=junit/test-results.xml
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        if: (!cancelled())
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            junit/*.xml
          github_token: ${{ steps.generate-token.outputs.token }}
